import java.awt.Image;

import javax.swing.ImageIcon;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Scale.java
//  @ Date : 2016.03.27.
//  @ Author : 
//
//




public class Scale extends Tile {
	private Coord door;
	public Map map;
	public Useable objects[] = new Useable [10];
	public int pressedweight;
	private int objcount = 0;
	
	public Scale(Coord location, Coord door, Map map){
		super(location);
		//System.out.println("Scale: konsturktor hívás");
		this.door = door;
		this.map = map;
	//	objects=new Useable() [] ;
		pressedweight=0;
        type="scale";
	}
	
	@Override
	public boolean setObj(Useable object) {
		if(object!=null){
		
		pressedweight+=object.getweight();

		objects[objcount]=object;	
		this.object = objects[objcount];
		
		objcount++;
		
		if( pressedweight>=100)	
			map.map[door.getY()][door.getX()].openDoor();
			
			return true;
		
		}
		else {
			return false;
		}
		
	}
	@Override
	public Useable getObj() {
		
		return object;
	}
	
	@Override
	public Useable takeObj(){
		int act=objcount-1;
		objcount--;
		
		if(act>=0)
		{
			if(act==0)
				object=null;
			else 
				object=objects[act-1];
		
			pressedweight-=objects[act].getweight();
		
			if( pressedweight<100)
				map.map[door.getY()][door.getX()].closeDoor();
			
			if(act==0)
				object=null;
			
			Useable temp = objects[act];
			objects[act]= null;
			
			return temp;
		}
		else 
			object=null;
		
		return object;
	}


	@Override
	public Coord stepOn(Coord c) {
		
		map.map[door.getY()][door.getX()].openDoor();
		
		return location;
		
	}
	
	@Override
	public void stepoff(){
		if( pressedweight<100)	
		map.map[door.getY()][door.getX()].closeDoor();
	}
}
