import java.awt.Image;

import javax.swing.ImageIcon;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Scale.java
//  @ Date : 2016.03.27.
//  @ Author : 
//
//




public class Scale extends Tile {
	private Coord door;
	public Map map;
	
	public Scale(Coord location, Coord door, Map map){
		super(location);
		//System.out.println("Scale: konsturktor hívás");
		this.door = door;
		this.map = map;
		ImageIcon ic = new ImageIcon("scale.jpg");
        image = ic.getImage();
	}
	
	@Override
	public boolean setObj(Useable object) {
		//System.out.println("Scale: setObj metódus hívás");
		this.object = object;
		
		if(object != null){	
			map.map[door.getY()][door.getX()].openDoor();
			return true;
		}
		else {
			return false;
		}
		
	}
	@Override
	public Useable getObj() {
		//System.out.println("Scale: getObj metódus hívás");
		map.map[door.getX()][door.getY()].closeDoor();
		return object;
	}


	@Override
	public Coord stepOn(Coord c) {
		//System.out.println("Scale stepon metódus");
		map.map[door.getY()][door.getX()].openDoor();
		//System.out.println(door.getX()+"  "+door.getY());
		return location;
		
	}
	
	@Override
	public void stepoff(){
		map.map[door.getY()][door.getX()].closeDoor();
	}
}
