import java.awt.Image;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Tile.java
//  @ Date : 2016.03.27.
//  @ Author : 
//
//




public abstract class Tile {
	public Useable object;
	public Coord location;
	public boolean isOpen;
	protected String type = "tile";
	public Tile(){}
	
	public String getType(){ return type;}
	
	public Tile(Coord c) {
		object = null;
		location = c;
	}
	
	
	public Coord getLoc() {
		return location;
	}
	
	public abstract Coord stepOn(Coord c);
	
	public Useable getObj() {
		//System.out.println("Tile: getObj metódus hívás");
		return object;
	}
	
	 public boolean fly(Bullet b)
	 {

		 return true;
	 }
	
	public void stepoff(){};
	public void openDoor(){};
	public void closeDoor(){};
	public void setWH(WormHole wh){};
	
	public Useable takeObj(){
				return object;
	}

	
	public boolean setObj(Useable o) {
		if(o==null)
			object=o;	
		if(object == null){	
			this.object = o;
			return true;
		}
		else 
		{
			return false;
		}	
	}
    
}
