import java.awt.Image;

import javax.swing.ImageIcon;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Useable.java
//  @ Date : 2016.03.27.
//  @ Author : 
//
//



//Abstract osztály használati tárgyak leírására
public abstract class Useable {
	public  Image image;
	static protected int  ZPMCount=0;
	
	public abstract  void redeem(); //A használható objektumokkal való interakciót írja le
	{
	}
	public int getZPMcount(){
		return ZPMCount;
	}
    
    public Image getImage() { 	return image; }
}
